# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ed1cd9839cab10357476ddbb79f674edffd4cd8213985b9361a22717ed5ee3754bf059654078e064c989c91650fa503a8b69d57938f910365d3856c236dfca80

test:
  secret_key_base: 192c728e638cd1319f7f53e58469e513125624c1b92762d3b2e7ba959e6152639c3b559dbf145bdee1492a3afad6cb48af1cc11995a379382088cb0baf795fe2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
